### ISSUE TITLE
cmd/cueckoo: importpt should not attempt to rebase onto tip of target branch

### ISSUE THREAD

**Issue by myitcv** [cue-sh/tools#29]
When importing a PR via `cueckoo importpr` we should, IMHO, not attempt to rebase onto the tip of the target branch. If I run `importpr` that's all I'm expecting it to do. Perhaps there could be a rebase flag, but I would argue even that is not essential because I can simply rebase after running the import if that's what I want to do.

The problem is that right now the `importpr` can fail if there is a conflict that needs to be resolved. That should be resolved as a later step.

Thoughts @mvdan?

**Comment by mvdan** [comment]
You're right that rebasing on the target branch isn't strictly necessary. I personally always do that, so I made `importpr` do it for the sake of automating more of my workflow.

I think we also want to encourage rebasing on the target branch in general. Otherwise actions like `runtrybot` may be testing old code.

That said, right now we do more than a plain rebase - we also squash commits. I think we want to keep the squashing on at all times, because otherwise `importpr` may result in multiple CLs from a single PR. It's quite common for external contributors to update a PR by adding more commits, expecting the merger to squash.

Rather than adding a flag and remembering to use it correctly, how about having `importpr` try to rebase onto the target branch like it does now, and if it fails due to conflicts, print a warning and fall back to just squashing without any rebasing? That feels like it will keep a good default, avoiding the footgun that is "I used impotpr and then ran the trybots on very old code because I forgot to rebase", while still keeping the rebase conflicts edge case working.

**Comment by myitcv** [comment]
> Rather than adding a flag and remembering to use it correctly, how about having `importpr` try to rebase onto the target branch like it does now, and if it fails due to conflicts, print a warning and fall back to just squashing without any rebasing?

I would honestly just keep it simple for now. Import the PR as it stands. If some other action is required later, then let me the user decide that. 

I'll raise a PR to this effect now because it's semi-blocking what we're doing with cuelang.org.

**Comment by mvdan** [comment]
Ack. If you do that, then perhaps leave the rebase+squash step behind an opt-in flag, because I do want to keep using that. Having to do it by hand would be unfortunate busy work :)

**Comment by mvdan** [comment]
Fixed by https://github.com/cue-sh/tools/pull/30, I'm pretty sure. Please reopen if I got that wrong.
