### ISSUE TITLE
cmd/cueckoo: issues are closed prematurely

### ISSUE THREAD

**Issue by 4ad** [cue-sh/tools#47]
This is reproductible and has happened to me thrice in cue-lang/cue-py.

See for example cue-lang/cue#3190 and https://review.gerrithub.io/c/cue-lang/cue-py/+/1196825.

Every time I push to gerrit (and this includes updates to existing CLs), `cmd/cueckoo` prematurely closes the issue.

How to reproduce:

1. pick an existing cue-lang/cue issue.
2. prepare a CL for `cue-py` that says in its commit message `Fixes cue-lang/cue#3190.` Evidently change the issue number.
3. run `git codereview mail`

Note that I use `Fixes cue-lang/cue#3190` instead of `Fixes #3190` because the issue lives in a different repository  than what we're pushing to (cue vs. cue-py), otherwise autohotlinking would not work. That might be relevant.

**Comment by jpluscplusm** [comment]
I believe this is happening because https://github.com/cue-lang/cue-trybot has a default branch of `main`, unlike the other trybot repos (e.g. https://github.com/cue-lang/cuelang.org-trybot/: `readme`).

When the trybots are triggered, commits are being pushed to the `main` branch by cueckoo. Because this is the default, GitHub sees this commit as being sufficient to close the associated issue (cf. https://github.blog/2013-01-22-closing-issues-via-commit-messages/).

I suspect that changing the trybot repo's default branch to some throw-away (e.g. the `readme` example of https://github.com/cue-lang/cue-trybot) will fix this. We don't do /anything/ with default branches via Terraform, in either side of the repo pair, so I suspect it'd be safe to switch this manually (though it'd probably be worth figuring out why this has affected this repo alone - maybe some `main`/`master` distinction, as we're using `master` most other places?)

**Comment by myitcv** [comment]
Great analysis, thanks @jpluscplusm. 

This should now be fixed: the default branch of the `cue-py-trybot` repo has been updated to follow the pattern elsewhere:

https://github.com/cue-lang/cue-py-trybot
